# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eC4MfCB-rWbs8lqjvvU_V4TFpoeuO3hK
"""

import streamlit as st
import pandas as pd

# Thiết lập giao diện Web
st.set_page_config(page_title="Game Optimizer Pro", page_icon="🎮", layout="wide")
st.title("🎮 Hệ Thống Tối Ưu Hóa Gói Nạp Game")
st.markdown("---")

# 1. ĐỌC VÀ XỬ LÝ DỮ LIỆU TỰ ĐỘNG
@st.cache_data
def load_data():
    xls = pd.ExcelFile('GameOptimization.xlsx')
    df_gemcard = pd.read_excel(xls, 'GemCard')

    # Xử lý cột Value: xóa dấu chấm, chữ ' đ' và ép kiểu số nguyên
    df_gemcard['Value'] = df_gemcard['Value'].astype(str).str.replace('.', '', regex=False).str.replace(' đ', '', regex=False).str.strip().astype(int)

    # Tách dataframe
    df_gem = df_gemcard[df_gemcard['Pack'].str.startswith('Gem')].copy()
    df_card = df_gemcard[df_gemcard['Pack'].str.startswith('Card')].copy()
    df_gold = pd.read_excel(xls, 'Gold')
    df_combo = pd.read_excel(xls, 'Combo')

    return df_gem, df_card, df_gold, df_combo

df_gem, df_card, df_gold, df_combo = load_data()

# 2. TÍNH TỶ GIÁ GỐC DỰA TRÊN GÓI RẺ NHẤT (BEST VALUE)
gem_base_rate = (df_gem['Value'] / df_gem['Qnt']).min()  # VND / 1 Ngọc
card_base_rate = (df_card['Value'] / df_card['Qnt']).min() # VND / 1 Thẻ
gold_base_rate = (df_gold['Gem2trade'] / df_gold['Qnt']).min() * gem_base_rate # VND / 1 Vàng

# 3. THUẬT TOÁN TỐI ƯU HÓA (UNBOUNDED KNAPSACK)
def optimize_knapsack(budget, df, name_col, weight_col, value_col, scale=1):
    # scale dùng để rút gọn số 0 cho VND chạy nhanh hơn
    budget_scaled = int(budget / scale)
    items = []
    for _, row in df.iterrows():
        items.append({
            'name': row[name_col],
            'weight': int(row[weight_col] / scale),
            'value': float(row[value_col])
        })

    dp = [0.0] * (budget_scaled + 1)
    choice = [-1] * (budget_scaled + 1)

    for w in range(1, budget_scaled + 1):
        for i, item in enumerate(items):
            if item['weight'] <= w:
                if dp[w - item['weight']] + item['value'] > dp[w]:
                    dp[w] = dp[w - item['weight']] + item['value']
                    choice[w] = i

    # Truy vết các gói đã chọn
    res = {}
    curr = budget_scaled
    while curr > 0 and choice[curr] != -1:
        idx = choice[curr]
        name = items[idx]['name']
        res[name] = res.get(name, 0) + 1
        curr -= items[idx]['weight']

    remaining_budget = curr * scale
    return res, dp[budget_scaled], remaining_budget


# ==========================================
# GIAO DIỆN NGƯỜI DÙNG (UI)
# ==========================================
col1, col2 = st.columns(2)

# --- PART 1: TỪ TIỀN SANG NGỌC/THẺ ---
with col1:
    st.header("💸 Part 1: Nạp Tiền Thật")
    budget_input = st.number_input("1. Bạn có bao nhiêu tiền (VND)?", min_value=0, step=10000, value=500000)
    target_1 = st.radio("2. Bạn muốn mua gì?", ["Ngọc (Gems)", "Thẻ (Cards)"], horizontal=True)

    if st.button("Tối ưu Nạp", type="primary"):
        if target_1 == "Ngọc (Gems)":
            res, max_val, rem = optimize_knapsack(budget_input, df_gem, 'Pack', 'Value', 'Qnt', scale=1000)
            target_name = "Ngọc"
        else:
            res, max_val, rem = optimize_knapsack(budget_input, df_card, 'Pack', 'Value', 'Qnt', scale=1000)
            target_name = "Thẻ"

        st.success("✅ **KẾT QUẢ TỐI ƯU:**")
        st.write(f"- **Tổng {target_name} nhận được:** {int(max_val):,} 💎")
        st.write(f"- **Tiền thật còn thừa:** {int(rem):,} VND")
        st.write("- **Các gói cần mua:**")
        for k, v in res.items():
            st.write(f"  📦 Mua **{v}x** gói `{k}`")

        # Lưu Ngọc/Thẻ vào session để pass sang Part 2 nếu muốn
        if target_1 == "Ngọc (Gems)":
            st.session_state['current_gems'] = int(max_val)

# --- PART 2: TỪ NGỌC ĐỔI SANG TÀI NGUYÊN ---
with col2:
    st.header("💎 Part 2: Quy Đổi Ngọc")
    # Tự động lấy Ngọc từ Part 1 nếu có
    default_gems = st.session_state.get('current_gems', 1000)
    gem_input = st.number_input("1. Bạn có bao nhiêu Ngọc?", min_value=0, step=100, value=default_gems)

    target_2 = st.selectbox("2. Bạn muốn đổi từ Ngọc sang gì?", ["Vàng (Gold)", "Combo (Vàng + Thẻ)"])

    goal_options = ["Tối đa số lượng Vàng", "ROI lớn nhất (Giá trị VND thực tế lớn nhất)"]
    goal_2 = st.selectbox("3. Mục tiêu của bạn là gì?", goal_options)

    # Điều kiện giữ lại Ngọc
    st.write("4. Bạn có điều kiện gì về Ngọc không? (Optional)")
    cond_col1, cond_col2 = st.columns([1, 2])
    operator = cond_col1.selectbox("Điều kiện", ["Không", "Giữ lại ít nhất (>=)"])
    min_gems_left = cond_col2.number_input("Số Ngọc", min_value=0, step=50, value=300)

    if st.button("Tối ưu Quy Đổi", type="primary"):
        # Tính toán budget ngọc được phép tiêu
        usable_gems = gem_input
        if operator == "Giữ lại ít nhất (>=)":
            usable_gems = gem_input - min_gems_left

        if usable_gems < 0:
            st.error("❌ Số Ngọc của bạn không đủ để đáp ứng điều kiện giữ lại!")
        else:
            if target_2 == "Vàng (Gold)":
                df_target = df_gold.copy()
                if goal_2 == "Tối đa số lượng Vàng":
                    df_target['Optimize_Value'] = df_target['Qnt']
                else: # ROI lớn nhất
                    df_target['Optimize_Value'] = df_target['Qnt'] * gold_base_rate

                res, max_val, rem = optimize_knapsack(usable_gems, df_target, 'Goldpack', 'Gem2trade', 'Optimize_Value')

                total_gold = sum([v * df_target[df_target['Goldpack']==k]['Qnt'].values[0] for k, v in res.items()])
                total_card = 0

            else: # Combo
                df_target = df_combo.copy()
                if goal_2 == "Tối đa số lượng Vàng":
                    df_target['Optimize_Value'] = df_target['Gold.Qnt']
                else: # ROI (Vàng * giá gốc + Thẻ * giá gốc)
                    df_target['Optimize_Value'] = (df_target['Gold.Qnt'] * gold_base_rate) + (df_target['Card.Qnt'] * card_base_rate)

                res, max_val, rem = optimize_knapsack(usable_gems, df_target, 'Combo', 'Gem2trade', 'Optimize_Value')

                total_gold = sum([v * df_target[df_target['Combo']==k]['Gold.Qnt'].values[0] for k, v in res.items()])
                total_card = sum([v * df_target[df_target['Combo']==k]['Card.Qnt'].values[0] for k, v in res.items()])

            st.success("✅ **KẾT QUẢ TỐI ƯU:**")
            st.write(f"- **Vàng thu được:** {int(total_gold):,} 🪙")
            if target_2 == "Combo (Vàng + Thẻ)":
                st.write(f"- **Thẻ thu được:** {int(total_card):,} 🃏")
                if goal_2 == "ROI lớn nhất (Giá trị VND thực tế lớn nhất)":
                    st.write(f"- **Giá trị thực tế (VND):** {int(max_val):,} đ *(Mức sinh lời tối đa)*")

            st.write(f"- **Số Ngọc còn dư (Chưa tiêu + Giữ lại):** {int(rem + (gem_input - usable_gems)):,} 💎")
            st.write("- **Chiến lược đổi gói:**")
            if res:
                for k, v in res.items():
                    st.write(f"  🛒 Đổi **{v}x** `{k}`")
            else:
                st.write("  ⚠️ *Không đủ Ngọc để đổi bất kỳ gói nào!*")